/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AdressPanel.java
 *
 * Created on Feb 23, 2012, 9:21:51 PM
 */
package imat;

import javax.swing.JOptionPane;
import java.io.FileWriter;
import java.io.PrintWriter;
import javax.swing.JButton;
import se.chalmers.ait.dat215.project.IMatDataHandler;

/**
 *
 * @author Gustav
 */
public class AdressPanel extends javax.swing.JPanel {

    /** Creates new form AdressPanel */
    public AdressPanel() {
        initComponents();
        loadAdressInfo();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(imat.IMatApp.class).getContext().getResourceMap(AdressPanel.class);
        setBackground(resourceMap.getColor("Form.background")); // NOI18N
        setFont(resourceMap.getFont("Form.font")); // NOI18N
        setName("Form"); // NOI18N
        setPreferredSize(new java.awt.Dimension(600, 400));

        jTextField1.setFont(resourceMap.getFont("FirstNameTextField.font")); // NOI18N
        jTextField1.setForeground(resourceMap.getColor("FirstNameTextField.foreground")); // NOI18N
        jTextField1.setText(resourceMap.getString("FirstNameTextField.text")); // NOI18N
        jTextField1.setName("FirstNameTextField"); // NOI18N

        jTextField2.setFont(resourceMap.getFont("LastNameTextField.font")); // NOI18N
        jTextField2.setForeground(resourceMap.getColor("LastNameTextField.foreground")); // NOI18N
        jTextField2.setText(resourceMap.getString("LastNameTextField.text")); // NOI18N
        jTextField2.setName("LastNameTextField"); // NOI18N

        jTextField3.setFont(resourceMap.getFont("AdressTextField.font")); // NOI18N
        jTextField3.setForeground(resourceMap.getColor("AdressTextField.foreground")); // NOI18N
        jTextField3.setText(resourceMap.getString("AdressTextField.text")); // NOI18N
        jTextField3.setName("AdressTextField"); // NOI18N

        jTextField4.setFont(resourceMap.getFont("PostAdressTextField.font")); // NOI18N
        jTextField4.setForeground(resourceMap.getColor("PostAdressTextField.foreground")); // NOI18N
        jTextField4.setText(resourceMap.getString("PostAdressTextField.text")); // NOI18N
        jTextField4.setToolTipText(resourceMap.getString("PostAdressTextField.toolTipText")); // NOI18N
        jTextField4.setName("PostAdressTextField"); // NOI18N

        jTextField5.setFont(resourceMap.getFont("CityTextField.font")); // NOI18N
        jTextField5.setForeground(resourceMap.getColor("CityTextField.foreground")); // NOI18N
        jTextField5.setText(resourceMap.getString("CityTextField.text")); // NOI18N
        jTextField5.setName("CityTextField"); // NOI18N

        jLabel1.setFont(resourceMap.getFont("Header.font")); // NOI18N
        jLabel1.setText(resourceMap.getString("Header.text")); // NOI18N
        jLabel1.setName("Header"); // NOI18N

        jSeparator1.setName("jSeparator1"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setFont(resourceMap.getFont("FirstNameLabel.font")); // NOI18N
        jLabel3.setText(resourceMap.getString("FirstNameLabel.text")); // NOI18N
        jLabel3.setName("FirstNameLabel"); // NOI18N

        jLabel4.setFont(resourceMap.getFont("LastNameLabel.font")); // NOI18N
        jLabel4.setText(resourceMap.getString("LastNameLabel.text")); // NOI18N
        jLabel4.setName("LastNameLabel"); // NOI18N

        jLabel5.setFont(resourceMap.getFont("AdressLabel.font")); // NOI18N
        jLabel5.setText(resourceMap.getString("AdressLabel.text")); // NOI18N
        jLabel5.setName("AdressLabel"); // NOI18N

        jLabel6.setFont(resourceMap.getFont("PostadressLabel.font")); // NOI18N
        jLabel6.setText(resourceMap.getString("PostadressLabel.text")); // NOI18N
        jLabel6.setName("PostadressLabel"); // NOI18N

        jCheckBox1.setBackground(resourceMap.getColor("Save.background")); // NOI18N
        jCheckBox1.setFont(resourceMap.getFont("Save.font")); // NOI18N
        jCheckBox1.setForeground(resourceMap.getColor("Save.foreground")); // NOI18N
        jCheckBox1.setText(resourceMap.getString("Save.text")); // NOI18N
        jCheckBox1.setToolTipText(resourceMap.getString("Save.toolTipText")); // NOI18N
        jCheckBox1.setName("Save"); // NOI18N

        jButton1.setIcon(resourceMap.getIcon("ToPaymentOptionsButton.icon")); // NOI18N
        jButton1.setText(resourceMap.getString("ToPaymentOptionsButton.text")); // NOI18N
        jButton1.setName("ToPaymentOptionsButton"); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextField5))
                                .addComponent(jCheckBox1)
                                .addComponent(jTextField2)
                                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                                .addComponent(jTextField3))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2)
                            .addGap(155, 155, 155)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(1, 1, 1)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox1)))
                .addGap(63, 63, 63)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
    saveAdressInfo();
}//GEN-LAST:event_jButton1MouseClicked

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jButton1ActionPerformed

public JButton getDoneButton() {
    return jButton1;
}
    private void loadAdressInfo() {
        this.jTextField5.setText(IMatDataHandler.getInstance().getCustomer().getPostAddress());
        this.jTextField4.setText(IMatDataHandler.getInstance().getCustomer().getPostCode());
        this.jTextField3.setText(IMatDataHandler.getInstance().getCustomer().getAddress());
        this.jTextField2.setText(IMatDataHandler.getInstance().getCustomer().getLastName());
        this.jTextField1.setText(IMatDataHandler.getInstance().getCustomer().getFirstName());
    }

    private void saveAdressInfo() {
            IMatDataHandler.getInstance().getCustomer().setFirstName(this.jTextField1.getText());
            IMatDataHandler.getInstance().getCustomer().setLastName(this.jTextField2.getText());
            IMatDataHandler.getInstance().getCustomer().setAddress(this.jTextField3.getText());
            IMatDataHandler.getInstance().getCustomer().setPostCode(this.jTextField4.getText());
            IMatDataHandler.getInstance().getCustomer().setPostAddress(this.jTextField5.getText());
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
