/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ProductPanel.java
 *
 * Created on Feb 27, 2012, 6:41:21 PM
 */
package imat;

import java.awt.*;
import javax.swing.*;
import se.chalmers.ait.dat215.project.*;

/**
 *
 * @author e
 */
public class OrderPanel extends javax.swing.JPanel {
    
    private IMatDataHandler data = IMatDataHandler.getInstance();
    private Order order;
    private Color typBrun = new Color(195, 182, 154);
    
    /** Creates new form ProductPanel */
    
    public OrderPanel(Order o){
        order = o;
        initComponents();
        initMyComponents();  
        this.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, typBrun));
        this.repaint();
        this.revalidate();
    }
   

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        orderPanel = new javax.swing.JPanel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0));
        orderLabel = new javax.swing.JLabel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0));
        datePanel = new javax.swing.JPanel();
        dateLabel = new javax.swing.JLabel();
        detailButton = new javax.swing.JButton();

        jPanel1.setName("jPanel1"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(imat.IMatApp.class).getContext().getResourceMap(OrderPanel.class);
        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N

        setBackground(resourceMap.getColor("Form.background")); // NOI18N
        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        setMaximumSize(new java.awt.Dimension(32767, 55));
        setMinimumSize(new java.awt.Dimension(0, 55));
        setName("Form"); // NOI18N

        orderPanel.setBackground(resourceMap.getColor("orderPanel.background")); // NOI18N
        orderPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        orderPanel.setMinimumSize(new java.awt.Dimension(0, 30));
        orderPanel.setName("orderPanel"); // NOI18N
        orderPanel.setLayout(new javax.swing.BoxLayout(orderPanel, javax.swing.BoxLayout.LINE_AXIS));

        filler2.setName("filler2"); // NOI18N
        orderPanel.add(filler2);

        orderLabel.setFont(resourceMap.getFont("orderLabel.font")); // NOI18N
        orderLabel.setText(resourceMap.getString("orderLabel.text")); // NOI18N
        orderLabel.setName("orderLabel"); // NOI18N
        orderPanel.add(orderLabel);

        filler3.setName("filler3"); // NOI18N
        orderPanel.add(filler3);

        filler1.setName("filler1"); // NOI18N
        orderPanel.add(filler1);

        datePanel.setBackground(resourceMap.getColor("datePanel.background")); // NOI18N
        datePanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        datePanel.setName("datePanel"); // NOI18N

        dateLabel.setBackground(resourceMap.getColor("dateLabel.background")); // NOI18N
        dateLabel.setFont(resourceMap.getFont("dateLabel.font")); // NOI18N
        dateLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dateLabel.setText(resourceMap.getString("dateLabel.text")); // NOI18N
        dateLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        dateLabel.setName("dateLabel"); // NOI18N

        detailButton.setText(resourceMap.getString("detailButton.text")); // NOI18N
        detailButton.setName("detailButton"); // NOI18N

        javax.swing.GroupLayout datePanelLayout = new javax.swing.GroupLayout(datePanel);
        datePanel.setLayout(datePanelLayout);
        datePanelLayout.setHorizontalGroup(
            datePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, datePanelLayout.createSequentialGroup()
                .addComponent(dateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(detailButton)
                .addContainerGap())
        );
        datePanelLayout.setVerticalGroup(
            datePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(dateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                .addComponent(detailButton))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(orderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(datePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(orderPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
            .addComponent(datePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dateLabel;
    private javax.swing.JPanel datePanel;
    private javax.swing.JButton detailButton;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel orderLabel;
    private javax.swing.JPanel orderPanel;
    // End of variables declaration//GEN-END:variables

    private void initMyComponents() {

        orderLabel.setFont(new Font("fans serif", Font.BOLD, 14));
        orderLabel.setText("" + order.getOrderNumber());
        dateLabel.setFont(new Font("Georgia", Font.PLAIN, 14));
        dateLabel.setText("" + order.getDate());
        
        orderPanel.setBorder(BorderFactory.createMatteBorder(0, 0, 0, 0, typBrun));
        datePanel.setBorder(BorderFactory.createMatteBorder(0, 0, 0, 0, typBrun));
    }
    
    public JButton getDetailButton() {
        return detailButton;
    }
}
    
    

