/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PaymentPanel.java
 *
 * Created on 2012-feb-28, 19:56:14
 */
package imat;

import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.*;

/**
 *
 * @author lisastenberg
 */
public class PaymentPanel extends javax.swing.JPanel {
    private VisaCardPanel v;
    private FakturaPanel f;
    private JPanel j; 
    
    /** Creates new form PaymentPanel */
    public PaymentPanel() {
        initComponents();
        v = new VisaCardPanel();
        f = new FakturaPanel();
        j = new JPanel();
        j.setBackground(new Color(252,251,237));
        cardPanel.add(v, "visa");
        cardPanel.add(f, "faktura");
        cardPanel.add(j, "kontant");
        
    }
    
    public JButton getDoneButton() {
        return doneButton;
    }
    
    public void changePanel(String s) {
        CardLayout c = (CardLayout)(cardPanel.getLayout());
        c.show(cardPanel, s);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        cardPanel = new javax.swing.JPanel();
        visaButton = new javax.swing.JRadioButton();
        fakturaButton = new javax.swing.JRadioButton();
        kontantButton = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        doneButton = new javax.swing.JButton();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(imat.IMatApp.class).getContext().getResourceMap(PaymentPanel.class);
        setBackground(resourceMap.getColor("Form.background")); // NOI18N
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setName("Form"); // NOI18N
        setPreferredSize(new java.awt.Dimension(623, 429));
        setSize(new java.awt.Dimension(623, 429));

        cardPanel.setName("cardPanel"); // NOI18N
        cardPanel.setLayout(new java.awt.CardLayout());

        buttonGroup1.add(visaButton);
        visaButton.setSelected(true);
        visaButton.setText(resourceMap.getString("visaButton.text")); // NOI18N
        visaButton.setName("visaButton"); // NOI18N
        visaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visaButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(fakturaButton);
        fakturaButton.setText(resourceMap.getString("fakturaButton.text")); // NOI18N
        fakturaButton.setName("fakturaButton"); // NOI18N
        fakturaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fakturaButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(kontantButton);
        kontantButton.setText(resourceMap.getString("kontantButton.text")); // NOI18N
        kontantButton.setName("kontantButton"); // NOI18N
        kontantButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kontantButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jSeparator1.setName("jSeparator1"); // NOI18N

        doneButton.setText(resourceMap.getString("doneButton.text")); // NOI18N
        doneButton.setName("doneButton"); // NOI18N

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jSeparator1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 581, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(visaButton)
                            .add(fakturaButton)
                            .add(kontantButton))
                        .add(18, 18, 18)
                        .add(cardPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel1)
                    .add(doneButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 176, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .add(2, 2, 2)
                .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(visaButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(fakturaButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(kontantButton))
                    .add(cardPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 301, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 9, Short.MAX_VALUE)
                .add(doneButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

private void fakturaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fakturaButtonActionPerformed
    changePanel("faktura");
}//GEN-LAST:event_fakturaButtonActionPerformed

private void visaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visaButtonActionPerformed
    changePanel("visa");
}//GEN-LAST:event_visaButtonActionPerformed

private void kontantButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kontantButtonActionPerformed
    changePanel("kontant");
}//GEN-LAST:event_kontantButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel cardPanel;
    private javax.swing.JButton doneButton;
    private javax.swing.JRadioButton fakturaButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton kontantButton;
    private javax.swing.JRadioButton visaButton;
    // End of variables declaration//GEN-END:variables
}
