/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ReceiptRowPanel.java
 *
 * Created on 2012-feb-29, 17:29:21
 */
package imat;

/**
 *
 * @author lisastenberg
 */
public class ReceiptRowPanel extends javax.swing.JPanel {
    
    /** Creates new form ReceiptRowPanel */
    public ReceiptRowPanel(String product, String priceAmount, String total) {
        initComponents();
        productLabel.setText(product);
        priceAmountLabel.setText(priceAmount);
        totalCostLabel.setText(total);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0));
        productLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(15, 0), new java.awt.Dimension(15, 0), new java.awt.Dimension(15, 0));
        priceAmountLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(40, 0), new java.awt.Dimension(40, 0), new java.awt.Dimension(40, 0));
        totalCostLabel = new javax.swing.JLabel();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(imat.IMatApp.class).getContext().getResourceMap(ReceiptRowPanel.class);
        setBackground(resourceMap.getColor("Form.background")); // NOI18N
        setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, resourceMap.getColor("Form.border.matteColor"))); // NOI18N
        setMaximumSize(new java.awt.Dimension(32767, 55));
        setMinimumSize(new java.awt.Dimension(0, 55));
        setName("Form"); // NOI18N
        setPreferredSize(new java.awt.Dimension(579, 55));

        jPanel1.setBackground(resourceMap.getColor("jPanel1.background")); // NOI18N
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 1, resourceMap.getColor("jPanel1.border.matteColor"))); // NOI18N
        jPanel1.setMaximumSize(new java.awt.Dimension(32767, 55));
        jPanel1.setMinimumSize(new java.awt.Dimension(0, 55));
        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(144, 55));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        filler1.setName("filler1"); // NOI18N
        jPanel1.add(filler1);

        productLabel.setBackground(resourceMap.getColor("productLabel.background")); // NOI18N
        productLabel.setFont(resourceMap.getFont("productLabel.font")); // NOI18N
        productLabel.setText(resourceMap.getString("productLabel.text")); // NOI18N
        productLabel.setAlignmentX(0.5F);
        productLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        productLabel.setMaximumSize(new java.awt.Dimension(200, 55));
        productLabel.setMinimumSize(new java.awt.Dimension(0, 55));
        productLabel.setName("productLabel"); // NOI18N
        jPanel1.add(productLabel);

        jPanel2.setBackground(resourceMap.getColor("jPanel2.background")); // NOI18N
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 1, resourceMap.getColor("jPanel2.border.matteColor"))); // NOI18N
        jPanel2.setMaximumSize(new java.awt.Dimension(32767, 55));
        jPanel2.setMinimumSize(new java.awt.Dimension(0, 55));
        jPanel2.setName("jPanel2"); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(181, 55));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        filler2.setName("filler2"); // NOI18N
        jPanel2.add(filler2);

        priceAmountLabel.setBackground(resourceMap.getColor("priceAmountLabel.background")); // NOI18N
        priceAmountLabel.setFont(resourceMap.getFont("priceAmountLabel.font")); // NOI18N
        priceAmountLabel.setText(resourceMap.getString("priceAmountLabel.text")); // NOI18N
        priceAmountLabel.setAlignmentX(0.5F);
        priceAmountLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        priceAmountLabel.setMaximumSize(new java.awt.Dimension(144, 55));
        priceAmountLabel.setMinimumSize(new java.awt.Dimension(0, 55));
        priceAmountLabel.setName("priceAmountLabel"); // NOI18N
        jPanel2.add(priceAmountLabel);

        jPanel3.setBackground(resourceMap.getColor("jPanel3.background")); // NOI18N
        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jPanel3.setMaximumSize(new java.awt.Dimension(32767, 55));
        jPanel3.setMinimumSize(new java.awt.Dimension(0, 55));
        jPanel3.setName("jPanel3"); // NOI18N
        jPanel3.setPreferredSize(new java.awt.Dimension(240, 55));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        filler3.setName("filler3"); // NOI18N
        jPanel3.add(filler3);

        totalCostLabel.setBackground(resourceMap.getColor("totalCostLabel.background")); // NOI18N
        totalCostLabel.setFont(resourceMap.getFont("totalCostLabel.font")); // NOI18N
        totalCostLabel.setText(resourceMap.getString("totalCostLabel.text")); // NOI18N
        totalCostLabel.setAlignmentX(0.5F);
        totalCostLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        totalCostLabel.setMaximumSize(new java.awt.Dimension(30000, 55));
        totalCostLabel.setMinimumSize(new java.awt.Dimension(0, 55));
        totalCostLabel.setName("totalCostLabel"); // NOI18N
        jPanel3.add(totalCostLabel);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 168, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                .add(39, 39, 39)
                .add(jPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 284, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .add(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel priceAmountLabel;
    private javax.swing.JLabel productLabel;
    private javax.swing.JLabel totalCostLabel;
    // End of variables declaration//GEN-END:variables
}
