/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ShoppingCartPanel.java
 *
 * Created on Feb 27, 2012, 11:56:43 PM
 */
package imat;

import java.awt.*;
import javax.swing.*;
import se.chalmers.ait.dat215.project.*;

/**
 *
 * @author e
 */
public class ShoppingCartPanel extends javax.swing.JPanel {

    private Dimension iconDimension = new Dimension(40,40);
    private Product product;
    private int amount;
    private Double totalValue;
    private boolean isFavorite;
    
    String path;
    private ImageIcon addFavoritesIcon;
    private ImageIcon remChartIcon;
    private ImageIcon remFavoritesIcon;
    private ImageIcon plusIcon;
    private ImageIcon minusIcon;
    
    private IMatDataHandler data = IMatDataHandler.getInstance();
    private Color typBrun = new Color(195, 182, 154);
    /** Creates new form ShoppingCartPanel */
    
    public ShoppingCartPanel(Product product, int amount, Double totalValue){
        initComponents();
        this.product = product;
        this.amount = amount;
        this.totalValue = totalValue;
        isFavorite = data.isFavorite(product);
        initMyComponents(product, amount, totalValue);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        leftPanel = new javax.swing.JPanel();
        productPicture = new javax.swing.JLabel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0));
        productName = new javax.swing.JLabel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        addToFavorites = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0));
        pricePanel = new javax.swing.JPanel();
        productPrice = new javax.swing.JLabel();
        rightPanel = new javax.swing.JPanel();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0));
        valueMinus = new javax.swing.JButton();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(3, 0), new java.awt.Dimension(3, 0), new java.awt.Dimension(3, 0));
        value = new javax.swing.JTextField();
        filler8 = new javax.swing.Box.Filler(new java.awt.Dimension(3, 0), new java.awt.Dimension(3, 0), new java.awt.Dimension(3, 0));
        valuePlus = new javax.swing.JButton();
        filler9 = new javax.swing.Box.Filler(new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 0));
        totalCost = new javax.swing.JLabel();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        removeFromChart = new javax.swing.JButton();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0));

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(imat.IMatApp.class).getContext().getResourceMap(ShoppingCartPanel.class);
        setBackground(resourceMap.getColor("Form.background")); // NOI18N
        setMaximumSize(new java.awt.Dimension(32767, 55));
        setMinimumSize(new java.awt.Dimension(0, 55));
        setName("Form"); // NOI18N

        leftPanel.setBackground(resourceMap.getColor("leftPanel.background")); // NOI18N
        leftPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        leftPanel.setMinimumSize(new java.awt.Dimension(0, 30));
        leftPanel.setName("leftPanel"); // NOI18N
        leftPanel.setLayout(new javax.swing.BoxLayout(leftPanel, javax.swing.BoxLayout.LINE_AXIS));

        productPicture.setFont(resourceMap.getFont("productPicture.font")); // NOI18N
        productPicture.setName("productPicture"); // NOI18N
        leftPanel.add(productPicture);

        filler2.setName("filler2"); // NOI18N
        leftPanel.add(filler2);

        productName.setFont(resourceMap.getFont("productName.font")); // NOI18N
        productName.setText(resourceMap.getString("productName.text")); // NOI18N
        productName.setName("productName"); // NOI18N
        leftPanel.add(productName);

        filler3.setName("filler3"); // NOI18N
        leftPanel.add(filler3);

        addToFavorites.setIcon(resourceMap.getIcon("addToFavorites.icon")); // NOI18N
        addToFavorites.setText(resourceMap.getString("addToFavorites.text")); // NOI18N
        addToFavorites.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        addToFavorites.setName("addToFavorites"); // NOI18N
        leftPanel.add(addToFavorites);

        filler1.setName("filler1"); // NOI18N
        leftPanel.add(filler1);

        pricePanel.setBackground(resourceMap.getColor("pricePanel.background")); // NOI18N
        pricePanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        pricePanel.setFont(resourceMap.getFont("pricePanel.font")); // NOI18N
        pricePanel.setName("pricePanel"); // NOI18N

        productPrice.setBackground(resourceMap.getColor("productPrice.background")); // NOI18N
        productPrice.setFont(resourceMap.getFont("productPrice.font")); // NOI18N
        productPrice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        productPrice.setText(resourceMap.getString("productPrice.text")); // NOI18N
        productPrice.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        productPrice.setName("productPrice"); // NOI18N

        javax.swing.GroupLayout pricePanelLayout = new javax.swing.GroupLayout(pricePanel);
        pricePanel.setLayout(pricePanelLayout);
        pricePanelLayout.setHorizontalGroup(
            pricePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(productPrice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
        );
        pricePanelLayout.setVerticalGroup(
            pricePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(productPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
        );

        rightPanel.setBackground(resourceMap.getColor("rightPanel.background")); // NOI18N
        rightPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        rightPanel.setMinimumSize(new java.awt.Dimension(0, 30));
        rightPanel.setName("rightPanel"); // NOI18N
        rightPanel.setLayout(new javax.swing.BoxLayout(rightPanel, javax.swing.BoxLayout.LINE_AXIS));

        filler5.setName("filler5"); // NOI18N
        rightPanel.add(filler5);

        valueMinus.setIcon(resourceMap.getIcon("valueMinus.icon")); // NOI18N
        valueMinus.setText(resourceMap.getString("valueMinus.text")); // NOI18N
        valueMinus.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        valueMinus.setName("valueMinus"); // NOI18N
        rightPanel.add(valueMinus);

        filler7.setName("filler7"); // NOI18N
        rightPanel.add(filler7);

        value.setBackground(resourceMap.getColor("value.background")); // NOI18N
        value.setFont(resourceMap.getFont("value.font")); // NOI18N
        value.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        value.setText(resourceMap.getString("value.text")); // NOI18N
        value.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        value.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        value.setDisabledTextColor(resourceMap.getColor("value.disabledTextColor")); // NOI18N
        value.setFocusable(false);
        value.setMaximumSize(new java.awt.Dimension(35, 25));
        value.setMinimumSize(new java.awt.Dimension(25, 25));
        value.setName("value"); // NOI18N
        value.setPreferredSize(new java.awt.Dimension(20, 20));
        rightPanel.add(value);

        filler8.setName("filler8"); // NOI18N
        rightPanel.add(filler8);

        valuePlus.setIcon(resourceMap.getIcon("valuePlus.icon")); // NOI18N
        valuePlus.setText(resourceMap.getString("valuePlus.text")); // NOI18N
        valuePlus.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        valuePlus.setName("valuePlus"); // NOI18N
        rightPanel.add(valuePlus);

        filler9.setName("filler9"); // NOI18N
        rightPanel.add(filler9);

        totalCost.setText(resourceMap.getString("totalCost.text")); // NOI18N
        totalCost.setName("totalCost"); // NOI18N
        rightPanel.add(totalCost);

        filler4.setName("filler4"); // NOI18N
        rightPanel.add(filler4);

        removeFromChart.setIcon(resourceMap.getIcon("removeFromChart.icon")); // NOI18N
        removeFromChart.setText(resourceMap.getString("removeFromChart.text")); // NOI18N
        removeFromChart.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        removeFromChart.setName("removeFromChart"); // NOI18N
        rightPanel.add(removeFromChart);

        filler6.setName("filler6"); // NOI18N
        rightPanel.add(filler6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(leftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pricePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
            .addComponent(leftPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
            .addComponent(pricePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addToFavorites;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.Box.Filler filler8;
    private javax.swing.Box.Filler filler9;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JPanel pricePanel;
    private javax.swing.JLabel productName;
    private javax.swing.JLabel productPicture;
    private javax.swing.JLabel productPrice;
    private javax.swing.JButton removeFromChart;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JLabel totalCost;
    private javax.swing.JTextField value;
    private javax.swing.JButton valueMinus;
    private javax.swing.JButton valuePlus;
    // End of variables declaration//GEN-END:variables

    private void initMyComponents(Product product, int amount, Double totalValue) {
        addIcons();
        changeMouseCursor();
        
        productPicture.setBorder(BorderFactory.createLineBorder(typBrun, 1));
        productName.setText(product.getName());
        productName.setFont(new Font("Georgia", Font.PLAIN, 14));
        productPrice.setText("" + product.getPrice() + " " + product.getUnit());
        productPrice.setFont(new Font("Georgia", Font.PLAIN, 14));
        productName.setFont(new Font("sans serif", Font.BOLD, 14));
        
        leftPanel.setBorder(BorderFactory.createMatteBorder(0, 0, 0, 1, typBrun));
        pricePanel.setBorder(BorderFactory.createMatteBorder(0, 0, 0, 0, typBrun));
        rightPanel.setBorder(BorderFactory.createMatteBorder(0, 1, 0, 0, typBrun));

        value.setText("" + amount);
        
        totalCost.setText("" + totalValue + " kr");
    }
    public JButton getFavoritesButton(){
        return addToFavorites;
    }
    public JButton getChartButton(){
        return removeFromChart;
    }
    public JButton getMinusButton(){
        return valueMinus;
    }
    public JButton getPlusButton(){
        return valuePlus;
    }
    public JTextField getValue(){
        return value;
    }
    public Product getProduct(){
        return product;
    }
    public void setFavoritesButton(){
         if(isFavorite){
            addToFavorites.setIcon(addFavoritesIcon);
            isFavorite = false;
            data.removeFavorite(this.product);
            addToFavorites.repaint();
            addToFavorites.revalidate();
        } else {
            addToFavorites.setIcon(remFavoritesIcon);
            isFavorite = true;
            data.addFavorite(this.product);
            addToFavorites.repaint();
            addToFavorites.revalidate();
        }        
    }
    public int getAmount(){
        return amount;
    }
    public Double getTotalValue(){
        return totalValue;
    }
    public void setAmount(int amount){
        this.amount = amount;
        value.setText("" + this.amount);       
    }
    public void setTotalValue(Double totalValue){
        this.totalValue = totalValue;
        totalCost.setText("" + totalValue + " kr");
    }
    public void addValue(){
        amount = amount + 1;
        value.setText("" + amount);
    }
    public void negValue(){
        if (amount != 1){
            amount = amount -1;
            value.setText("" + amount);
        }
    }
    public void zeroValue(){
        amount = 1;
        value.setText("" + amount);
    }
    public void changeMouseCursor(){
        addToFavorites.setCursor(new Cursor(Cursor.HAND_CURSOR));
        removeFromChart.setCursor(new Cursor(Cursor.HAND_CURSOR));
        valuePlus.setCursor(new Cursor(Cursor.HAND_CURSOR));
        valueMinus.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }

    private void addIcons() {
        path = "resources/bilder/";
        addFavoritesIcon = new ImageIcon(getClass().getResource(path + "laggtill_favoriter.png"));
        remFavoritesIcon = new ImageIcon(getClass().getResource(path + "tabort_favoriter.png"));
        remChartIcon = new ImageIcon(getClass().getResource(path + "tabort_kundvagn.png"));
        minusIcon = new ImageIcon(getClass().getResource(path + "minus.png"));
        plusIcon = new ImageIcon(getClass().getResource(path + "plus.png"));
        productPicture.setIcon(data.getImageIcon(product, iconDimension));
        removeFromChart.setIcon(remChartIcon);
        valuePlus.setIcon(plusIcon);
        valueMinus.setIcon(minusIcon);
        if(!isFavorite){
            addToFavorites.setIcon(addFavoritesIcon);
        } else {
            addToFavorites.setIcon(remFavoritesIcon);
        }
    }
}
